### ISSUE TITLE
Pull sample Message field segments

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/gloss#27]
For: 

Relevant Clinical Information
Specimen Source

**Comment by davidmiller** [comment]
Can we also pull the samples we have for: 

Admission 

Admission Source
Referral Source

**Comment by fredkingham** [comment]
@GabPoll @michaeledwardmarks, we're looking at the usefulness of specimen source, relevant clinical information, admission source and referral source. Can you let us know if they're useful?

for specimen source, we have the folowing in sample messages

 'gynaecology, SWVU^Swab - Vulva',
 'cytopathology, ^CervicalSample',
 'hepd, CLB^Clotted blood',
 'urine_culture_result_message, URIN^Urine',

Are the codes useful or shall we just keep the descriptions (ie not record SWVU but record "Swab - Vulva" (or neither?)

for relevent clinical information its mostly blank, but for hepd it states "TESTING DPL", is this useful?

In terms of admission source/referral source, there seems quite useful information, in our inpatients admission its, admission source - "Usual place of residence", referral source - "Social Servicers".

Which fields do you think are worth storing?

**Comment by michaeledwardmarks** [comment]
Descriptions useful. 
(Varies from test to test but as a general rule useful)

**Comment by GabPoll** [comment]
The specimen source description is definitely useful. Agree, without the SWVU, which is an in-house code presumably.

No idea what TESTING DPL stands for.

Usual place of residence is useful.

**Comment by davidmiller** [comment]
Great - thanks for that ! I think we have the right fields now so closing this.
